---
title: "[Work in progress] *postpb* tutorial"
date: "`r Sys.Date()`"
author: "Michael Gerth"
output:
  rmdformats::robobook:
    highlight: kate
---

This tutorial will guide you through *postpb* usage by explaining each of the panels in the app and their main functions.

# Orientation

After installing and starting *postpb* as described [here](https://github.com/gerthmicha/postpb#installation), make sure the app runs in your browser using full screen. If you are using Rstudio, it may display the app in its viewer. In that case, you can switch to the browser by clicking 'open in browser' in the viewer's top panel.

Similar to a regular website, *postpb* is organised in multiple pages (panels) which which can be accessed by clicking on the tabs on the very top the the screen ('Parameters', 'Trees', 'About'). While the latter contains some general information, the former 2 are where the analyses happen. Note that the panels are completely independent of each other, meaning that you can use one or both, and that you don't necessarily need to provide data from the same runs to both panels (although this is the typical use case).

# Example files

**Example 1** is taken from [Kocot et al. (2017)](https://doi.org/10.1093/sysbio/syw079), and contains the first 5,000 iterations of their *Phylobayes* analysis of the "LB_106" matrix under the CAT+GTR model. The example contains traces and trees for 4 chains. This is an example for a run that can be considered unsuccessful. Neither tree topologies nor trace samples show appropriate convergence and mixing.  

**Example 2** is a *MrBayes* analysis of the "primates" alignment that is distributed with *MrBayes* (https://github.com/NBISweden/MrBayes/tree/develop/examples) and is originally from [Hayasaka et al. (1988)](https://doi.org/10.1093/oxfordjournals.molbev.a040524). The analysis was run under a HKY+G model using 2x4 chains for 1,000,000 generations with a sampling frequency of 50. This is an example for a run that was successful. Tree and trace samples are mostly converged and well mixed. 

# File formats

When you start the app, you will likely have data from a Bayesian phylogenetic analysis. Typically, this would be 

1) Parameter or trace files that contain the values of various estimated model parameters over the length of the run, and
2) Tree files containing estimated phylogenies for each iteration of the run.

Depending on the software used, these files may look quite differently. *postpb* works best with output files from *Phylobayes* and *MrBayes*, but should work for other Bayesian phylogenetics software as well.

-   Parameter files are typically tabulator separated files, with one column per model parameter, and one line for each iteration or generation of the run. files produced by *Phylobayes* and *MrBayes* end in `.trace` or `.p`, respectively.\
-   Tree files contain one tree per iteration of the run. The most typical tree formats are Newick (e.g., used by Phylobayes, files end in `*.treelist`) and Nexus (used by MrBayes, `*.t` file ending).

Examples of all file types can be found in [the example folder](https://github.com/gerthmicha/postpb/tree/master/example) of this repository.

# The Parameters tab

When you start the app, the 'Parameters' tab will open automatically. You will notice that there is a side panel to the left, and a main display area to the right. The main display carries 4 tabs ('Traces', 'Violin', 'Density', 'Summary statistics'). The side panel is where you find all of the global options and settings, i.e., the settings that apply to each of the plots.

To get to know the app, it makes sense to use one of the examples. Click 'Load example 1' and wait for a plot to appear. Alternatively, upload your own data through the interface. 

## Sidebar

In the sidebar to the left, the following global options (i.e., applying to all trace plots) are available:

-   **Burnin** - the number of iterations to exclude from the beginning of the run. This defaults to 20% of the shortest chain, but it makes sense to play around with this (indeed, one of the aims of *postpb* is to allow you to choose a sensible burnin size).
-   **Select trace file** - it is recommended to have multiple runs and/or chains for your Bayesian phylogenetics analysis. Here, you can exclude selected chains from your *postpb* analysis. This may be sensible if one of your chains is a clear outlier.
-   **Sampling frequency** - How many data points from your Bayesian phylogeny do you want to analyse in *postpb*? The default value is 10, meaning only 10% of the run will be analysed. Due to the high autocorrelation in Bayesian phylogenetics analyses, this is often a good default. Keep in mind however that you may already have specified a reduced sampling frequency within e.g., *Phylobayes* or *Mr Bayes*. If you want to include the entire run, choose '1'. Low values here will result in longer run times of *postpb*. To apply changing the sampling frequency, click 'Apply'
-   **More options** - this button enables another suit of options that are all about the layout of the plots (size and number of columns). All changes will be applied immediately.
-   **Download pdf** - press this once happy with the look of your plots. A pdf will be generated.

**IMPORTANT:** The items in the main display area will update dynamically if any of the global options are changed. 

## Main display

Access the parameter plots by clicking through the different panels of the main display. Alter the global options (e.g., burnin and sampling frequency) to see how that affects descriptive plots and statistics. 

-   **Trace** - generates simple scatter plots of all variables over iteration of the analysis. This is a very common way of displaying results of a Bayesian analysis and is helpful in determining suitable burnin sizes. You can choose to have the scatter plots in lines, points, or both. Play around with the burnin slider and observe how the plot changes. 

-   **Violin** & **Density** - these very similar plots show the distribution of your parameters in the post-burnin sample. The plots are especially helpful in determining how similar the different chains are compared with each other.

- **Summary statistics** - here, the data is summarised once more using descriptive statistics. Click on the 'Toggle explanations' button to learn a bit about the different values and what they may mean for the interpretation of the run. For documentation purposes, the table of values can be copied to the clipboard (e.g., to paste them into a spreadsheet application), downloaded as `.csv` file or printed from the browser.  


# The Trees tab

Access the trees tab through the panel at the very top of the page. Again, using one of the examples is probably a good way of trying out the app. Alternatively, upload your tree files after selecting the appropriate file format. Once you uploaded tree data, *postpb* will begin calculating a consensus tree. Depending on the number of your trees, this may take some time. A popup will remind you to be patient here. 

Before checking out the tree, familiarise yourself with the global options (panel on the left). Much of this is very similar to the traces tab:

* **Burnin** & **Select trace files** - do exactly what they do in the traces tab.
* **Number of cores** - some of the most intense computations benefit from parallelisation. *postpb* will automatically detect the number of cores available on your machine and select one core fewer than the maximum number. Choose a lower value if you run many other processes parallel to *postpb* (but be prepared it may then take longer to run).
* 
